In [ ]:
import numpy as np

# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
# Add arrays
total_yield = field_a + field_b
print(total_yield)

# Subtract to find difference
difference = field_a - field_b
print(difference)

# Multiply each by a constant
doubled = field_a * 2
print(doubled)

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]


In [ ]:
# Square roots
areas = np.array([100, 144, 225, 169])
sides = np.sqrt(areas)

# Exponentiation
growth = np.exp([0, 1, 2])

# Logarithms
np.log10([10, 100, 1000])

array([1., 2., 3.])

In [ ]:
prices = np.array([19.99, 24.51, 30.25])
# Round to nearest integer
np.round(prices)

# Floor (round down)
np.floor(prices)

# Ceiling (round up)
np.ceil(prices)

array([20., 25., 31.])

In [ ]:
# Work with radians
angles = np.array([0, np.pi/2, np.pi])
sines = np.sin(angles)
cosines = np.cos(angles)
tangents = np.tan(angles)
print(angles)

[0.         1.57079633 3.14159265]


In [ ]:
daily_rainfall = np.array([0.2, 0.0, 0.5, 1.2, 0.3, 0.1, 0.0])
# Sum
total = np.sum(daily_rainfall)
# Output: 2.3
# Mean (average)
average = np.mean(daily_rainfall)
# Output: 0.328...
# Standard deviation
variability = np.std(daily_rainfall)
# Output: 0.404...
# Min and Max
driest = np.min(daily_rainfall)  # 0.0
wettest = np.max(daily_rainfall)  # 1.2
print(total)
print(average)
print(variability)
print(driest)
print(wettest)

2.3
0.32857142857142857
0.39175169145148825
0.0
1.2


In [ ]:
# Crop yields: 3 fields × 4 years
yields = np.array([
    [120, 125, 130, 135],
    [115, 120, 122, 128],
    [130, 135, 140, 142]
])
# Average across all data
overall_avg = np.mean(yields)

# Average per field (across years)
field_avgs = np.mean(yields, axis=1)

# Average per year (across fields)
year_avgs = np.mean(yields, axis=0)
print(overall_avg)
print(field_avgs)
print(year_avgs)


128.5
[127.5  121.25 136.75]
[121.66666667 126.66666667 130.66666667 135.        ]


In [ ]:
# Add scalar to array
temps = np.array([70, 72, 68])
adjusted = temps + 5
print(adjusted)

[75 77 73]


In [ ]:
# Base prices for 3 products
base_prices = np.array([[10], [20], [30]])  # 3×1
# Discounts for 4 stores
discounts = np.array([0.9, 0.85, 0.95, 0.88])  # 1×4
# Broadcast multiplication
final_prices = base_prices * discounts
print(final_prices)

[[ 9.   8.5  9.5  8.8]
 [18.  17.  19.  17.6]
 [27.  25.5 28.5 26.4]]


In [ ]:
# Simulated hourly temperature data (4 sensors × 24 hours)
np.random.seed(42) # For reproducibility
sensors = np.random.normal(loc=75, scale=5, size=(4, 24))
# Round to 1 decimal place
sensors = np.round(sensors, 1)
# Problem 1: Find all readings above 82°F (danger threshold)
overheating = sensors > 82
critical_temps = sensors[overheating]
print(f"Critical readings: {len(critical_temps)} occurrences")
print(f"Hottest reading: {np.max(sensors):.1f}°F")
# Problem 2: Calculate statistics per sensor
for i in range(4):
 sensor_data = sensors[i, :]
 print(f"Sensor {i+1}:")
 print(f" Average: {np.mean(sensor_data):.1f}°F")
 print(f" Range: {np.min(sensor_data):.1f}°F to {np.max(sensor_data):.1f}°F")
 print(f" Std Dev: {np.std(sensor_data):.1f}°F")
# Problem 3: Calculate hourly averages (across all sensors)
hourly_avg = np.mean(sensors, axis=0)
hottest_hour = np.argmax(hourly_avg)
print(f"Hottest hour: Hour {hottest_hour} ({hourly_avg[hottest_hour]:.1f}°F")

Critical readings: 7 occurrences
Hottest reading: 84.3°F
Sensor 1:
 Average: 74.3°F
 Range: 65.4°F to 82.9°F
 Std Dev: 4.8°F
Sensor 2:
 Average: 73.7°F
 Range: 65.2°F to 84.3°F
 Std Dev: 4.3°F
Sensor 3:
 Average: 75.5°F
 Range: 66.2°F to 82.7°F
 Std Dev: 4.3°F
Sensor 4:
 Average: 74.3°F
 Range: 61.9°F to 82.8°F
 Std Dev: 4.8°F
Hottest hour: Hour 17 (78.0°F


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]
slice_view[0] = 999
print(arr)

[  1 999   3   4   5]


In [ ]:
a = np.array([1, 2, 3])
result = a / 2
result = a // 2
print(result)

[0 1 1]


In [ ]:
# Float32 uses half the memory of float64
large_array = np.zeros((1000, 1000), dtype=np.float32

SyntaxError: incomplete input (ipython-input-2299229231.py, line 2)